added this dependency because it was giving me this error before when run in Docker when building with a clean anaconda image:
netuser@e7cc1872ff93:/tmp/pandas_tutor$ python -m pandas_tutor.main -c "import pandas as pd"
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/pandas_tutor/pandas_tutor/main.py", line 19, in <module>
    from .diagram import OutputSpec
  File "/tmp/pandas_tutor/pandas_tutor/diagram.py", line 15, in <module>
    from .parse_nodes import ParseSyntaxError
  File "/tmp/pandas_tutor/pandas_tutor/parse_nodes.py", line 11, in <module>
    from .util import Axis, CodeRange, Slicer
  File "/tmp/pandas_tutor/pandas_tutor/util.py", line 11, in <module>
    from typing_extensions import TypeGuard
ImportError: cannot import name 'TypeGuard' from 'typing_extensions' (/opt/conda/lib/python3.8/site-packages/typing_extensions.py)